environment: development
logLevel: info

api:
  host: localhost
  port: 8080
  endpoint: http://localhost:10332
  timeout: 30s
  enableCors: true
  maxRequestBodySize: 10485760 # 10MB

database:
  driver: postgres
  host: localhost
  port: 5432
  name: neo_service_layer
  user: postgres
  password: postgres
  sslMode: disable

neo:
  network: testnet
  rpc:
    - http://seed1t5.neo.org:20332
    - http://seed2t5.neo.org:20332
  blockTime: 15
  confirmations: 1

services:
  gasBank:
    initialGas: 1000
    refillAmount: 100
    refillThreshold: 10
    maxAllocationPerUser: 100
    minAllocationAmount: 1
    maxAllocationTime: 24h
    cooldownPeriod: 1h
    storeType: postgres
    monitorInterval: 5m

  priceFeed:
    updateInterval: 1m
    minDeviation: 0.5
    heartbeatTime: 24h
    sources:
      - binance
      - huobi
      - okex

  automation:
    checkInterval: 1m
    retryDelay: 5m
    maxExecutionTime: 5m
    maxRetries: 3

  functions:
    executionWindow: 5m
    maxMemory: 512
    maxTimeout: 30s
    defaultRuntime: python3.9

  trigger:
    maxTriggers: 100
    maxExecutions: 1000
    retentionPeriod: 720h # 30 days

  secrets:
    rotationInterval: 720h # 30 days
    storeType: postgres
    encryptionKey: ${SECRETS_ENCRYPTION_KEY}

  metrics:
    collectionInterval: 1m
    retentionPeriod: 2160h # 90 days
    exportFormat: prometheus

  logging:
    format: json
    retentionPeriod: 2160h # 90 days
    maxSize: 100
    maxBackups: 10

security:
  jwtSecret: ${JWT_SECRET}
  tokenExpiration: 24h
  allowedOrigins:
    - "*"

account:
  maxBatchSize: 50
  defaultGasLimit: 1000
  signatureTimeout: 60s
  recoveryWindow: 24h
  teeRequired: true