version: '3.8'

services:
  # Database and Cache Services
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({ping:1}).ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - neo-service-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - neo-service-network

volumes:
  mongodb-data:
  redis-data:

networks:
  neo-service-network:
    driver: bridge
