global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'neo-service-layer-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:80']

  - job_name: 'neo-service-layer-enclave'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['enclave:5000']
