global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'neo-service-layer'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scheme: http