# Gas Bank Service Configuration

# Gas Pool Configuration
pool:
  default_allocation: "1000000" # Default gas allocation for new users
  min_allocation: "100000"     # Minimum gas allocation
  max_allocation: "10000000"   # Maximum gas allocation
  refill:
    enabled: true
    interval: 24h              # How often to check for refills
    threshold: "100000"        # Refill when gas drops below this amount
    amount: "500000"          # Amount to refill
    max_attempts: 3           # Maximum refill attempts before alerting
  monitoring:
    enabled: true
    check_interval: 5m        # How often to check pool status
    alert_threshold: "50000"  # Alert when gas drops below this amount

# Gas Distribution
distribution:
  strategy: "fair_share"      # fair_share, priority, or weighted
  batch_size: 100            # Number of transactions to process in one batch
  priority_users:            # Users with special gas allocation rules
    - address: ${SYSTEM_ADDRESS}
      allocation_multiplier: 2.0
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    burst_size: 10

# Transaction Management
transactions:
  retry:
    enabled: true
    max_attempts: 3
    initial_interval: 1s
    max_interval: 10s
    multiplier: 2.0
  confirmation:
    required_blocks: 1       # Number of blocks to wait for confirmation
    timeout: 60s            # Maximum time to wait for confirmation
  optimization:
    enabled: true
    strategy: "cost_based"  # cost_based or speed_based
    max_fee_increase: 0.5   # Maximum fee increase for optimization

# Gas Price Oracle
price_oracle:
  enabled: true
  update_interval: 1m
  sources:
    - name: "neo_rpc"
      weight: 1.0
      timeout: 5s
  fallback_price: "0.001"   # Fallback price if oracle fails

# Storage Configuration
storage:
  type: "postgres"
  postgres:
    table_prefix: "gasbank_"
  retention:
    enabled: true
    duration: 90d           # How long to keep historical data

# Metrics and Monitoring
metrics:
  enabled: true
  collection_interval: 10s
  exporters:
    - type: "prometheus"
      endpoint: "/metrics"
  alerts:
    low_balance:
      threshold: "1000000"
      notification:
        type: "email"
        recipients: ["alerts@neo-service-layer.io"]

# Security
security:
  max_allocation_per_request: "1000000"
  blocked_addresses: []      # List of addresses to block
  whitelist_enabled: false
  whitelist_addresses: []    # List of addresses to whitelist if enabled

# Recovery
recovery:
  enabled: true
  backup_interval: 24h
  backup_retention: 7d
  auto_recover: true        # Automatically recover from failures

# Development
development:
  mock_transactions: false  # Use mock transactions for testing
  simulation_mode: false    # Run in simulation mode without real transactions
