# Logging Service Configuration

# Global Configuration
global:
  level: "info"
  format: "json"
  timestamp_format: "RFC3339"
  caller_info: true
  stack_trace:
    enabled: true
    level: "error"

# Output Configuration
outputs:
  console:
    enabled: true
    level: "info"
    format: "text"
    color: true
  file:
    enabled: true
    level: "debug"
    format: "json"
    path: "/var/log/neo-service/service.log"
    max_size: "100MB"
    max_age: 7
    max_backups: 5
    compress: true
  syslog:
    enabled: true
    level: "info"
    format: "json"
    network: "udp"
    address: "localhost:514"
    facility: "local0"
    tag: "neo-service"

# Service Specific Logging
services:
  api:
    level: "info"
    fields:
      service: "api"
      component: "http"
    request_logging:
      enabled: true
      exclude_paths: ["/health", "/metrics"]
      headers:
        include: ["User-Agent", "Content-Type"]
        exclude: ["Authorization"]
  functions:
    level: "info"
    fields:
      service: "functions"
      component: "runtime"
    execution_logging:
      enabled: true
      include_params: false
      include_result: false
  gasbank:
    level: "info"
    fields:
      service: "gasbank"
      component: "transactions"
  pricefeed:
    level: "info"
    fields:
      service: "pricefeed"
      component: "oracle"
  trigger:
    level: "info"
    fields:
      service: "trigger"
      component: "executor"
  secrets:
    level: "info"
    fields:
      service: "secrets"
      component: "vault"

# Aggregation and Processing
processing:
  sampling:
    enabled: true
    rate: 0.1
    rules:
      - match:
          level: "debug"
        rate: 0.01
  filtering:
    rules:
      - field: "path"
        pattern: "health|metrics"
        action: "drop"
  enrichment:
    enabled: true
    fields:
      environment: ${ENV:-production}
      region: ${REGION:-unknown}
      version: ${VERSION:-unknown}

# Storage and Retention
storage:
  type: "elasticsearch"
  elasticsearch:
    addresses: ["http://elasticsearch:9200"]
    index_prefix: "neo-service-logs"
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    retention:
      enabled: true
      days: 30
    template:
      enabled: true
      name: "neo-service"
      pattern: "neo-service-logs-*"
  backup:
    enabled: true
    interval: 24h
    retention: 7d

# Monitoring and Alerting
monitoring:
  metrics:
    enabled: true
    collection_interval: 10s
    exporters:
      - type: "prometheus"
        endpoint: "/metrics"
  alerts:
    error_rate:
      threshold: 100
      window: 5m
      notification:
        type: "email"
        recipients: ["alerts@neo-service-layer.io"]
    critical_logs:
      pattern: "error|fatal"
      threshold: 10
      window: 5m
      notification:
        type: "slack"
        channel: "#alerts"

# Security
security:
  encryption:
    enabled: true
    sensitive_fields: ["password", "token", "key"]
  redaction:
    enabled: true
    patterns:
      - "\\b\\d{16}\\b" # Credit card numbers
      - "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b" # Email addresses
  audit:
    enabled: true
    events:
      - "configuration_change"
      - "level_change"
      - "filter_change"

# Development
development:
  pretty_print: true
  debug_headers: false
  local_time: true
