global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'neo-service'
    static_configs:
      - targets: ['api:9090']

  - job_name: 'neo-node'
    static_configs:
      - targets: ['neo-node:10332']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 