# Secrets Service Configuration

# Encryption Configuration
encryption:
  provider: "azure_key_vault"  # azure_key_vault, aws_kms, or local
  key_rotation:
    enabled: true
    interval: 30d
    automatic: true
  azure_key_vault:
    vault_url: ${AZURE_KEY_VAULT_URL}
    tenant_id: ${AZURE_TENANT_ID}
    client_id: ${AZURE_CLIENT_ID}
    client_secret: ${AZURE_CLIENT_SECRET}
  aws_kms:
    region: ${AWS_REGION}
    key_id: ${AWS_KMS_KEY_ID}
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
  local:
    key_file: "./keys/master.key"
    backup_enabled: true
    backup_location: "./keys/backup/"

# Storage Configuration
storage:
  type: "postgres"          # postgres or vault
  postgres:
    table_prefix: "secrets_"
    encryption_enabled: true
  vault:
    address: ${VAULT_ADDR}
    token: ${VAULT_TOKEN}
    path_prefix: "neo/secrets"
  backup:
    enabled: true
    interval: 24h
    retention: 7d
    encryption_enabled: true

# Access Control
access_control:
  max_secrets_per_user: 1000
  max_secret_size: 10240    # 10KB
  allowed_secret_types:
    - "string"
    - "file"
    - "certificate"
  permissions:
    default_ttl: 3600       # 1 hour
    max_ttl: 2592000        # 30 days
    require_mfa: false
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# TEE Integration
tee:
  enabled: true
  provider: "azure_confidential_computing"
  attestation:
    required: true
    url: ${TEE_ATTESTATION_URL}
    token: ${TEE_ATTESTATION_TOKEN}
  memory_encryption: true
  secure_communication: true

# Audit Logging
audit:
  enabled: true
  log_level: "info"
  events:
    - "create"
    - "read"
    - "update"
    - "delete"
    - "rotate"
  retention:
    enabled: true
    duration: 90d
  exporters:
    - type: "file"
      path: "/var/log/secrets/audit.log"
    - type: "syslog"
      facility: "local0"

# Metrics and Monitoring
metrics:
  enabled: true
  collection_interval: 10s
  exporters:
    - type: "prometheus"
      endpoint: "/metrics"
  alerts:
    failed_operations:
      threshold: 5
      window: 5m
      notification:
        type: "email"
        recipients: ["alerts@neo-service-layer.io"]

# API Configuration
api:
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  authentication:
    methods:
      - "jwt"
      - "api_key"
    mfa:
      enabled: false
      providers:
        - "totp"
        - "sms"

# Recovery
recovery:
  enabled: true
  backup_interval: 24h
  backup_retention: 7d
  auto_recover: true

# Development
development:
  mock_encryption: false
  debug_logging: false
  test_keys:
    enabled: false
    path: "./test/keys/"
