# Trigger Service Configuration

# Trigger Types Configuration
types:
  schedule:
    enabled: true
    max_frequency: "1m"
    min_frequency: "1h"
    max_active_per_user: 100
    validation:
      cron_expression: true
      timezone: true

  event:
    enabled: true
    max_active_per_user: 100
    filters:
      max_conditions: 10
      allowed_operators:
        - "eq"
        - "gt"
        - "lt"
        - "gte"
        - "lte"
        - "contains"
    validation:
      contract_address: true
      event_name: true

  condition:
    enabled: true
    max_active_per_user: 100
    evaluation:
      timeout: 30s
      max_complexity: 10
      allowed_functions:
        - "abs"
        - "ceil"
        - "floor"
        - "round"
        - "max"
        - "min"

# Execution Configuration
execution:
  retry:
    enabled: true
    max_attempts: 3
    initial_interval: 1s
    max_interval: 10s
    multiplier: 2.0
  timeout: 60s
  concurrent_limit: 100
  batch:
    enabled: true
    size: 10
    interval: 1m

# Storage Configuration
storage:
  type: "postgres"
  postgres:
    table_prefix: "trigger_"
  retention:
    enabled: true
    duration: 90d
    execution_history: 30d
  backup:
    enabled: true
    interval: 24h
    retention: 7d

# Event Monitoring
monitoring:
  blockchain:
    poll_interval: 1s
    confirmation_blocks: 1
    max_blocks_per_scan: 100
  condition:
    evaluation_interval: 1m
    cache_duration: 5m
  schedule:
    timezone: "UTC"
    missed_trigger_threshold: 5m

# Queue Configuration
queue:
  type: "redis"
  redis:
    key_prefix: "trigger_"
    stream_max_len: 1000
  processing:
    batch_size: 100
    workers: 10
    timeout: 30s

# Metrics and Monitoring
metrics:
  enabled: true
  collection_interval: 10s
  exporters:
    - type: "prometheus"
      endpoint: "/metrics"
  alerts:
    execution_failure:
      threshold: 3
      window: 5m
      notification:
        type: "email"
        recipients: ["alerts@neo-service-layer.io"]
    missed_trigger:
      threshold: 5
      window: 1h
      notification:
        type: "email"
        recipients: ["alerts@neo-service-layer.io"]

# Security
security:
  max_triggers_per_user: 1000
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
  validation:
    contract_whitelist: []
    function_whitelist: []

# Recovery
recovery:
  enabled: true
  checkpoint_interval: 5m
  auto_resume: true
  max_replay_age: 24h

# Development
development:
  mock_events: false
  simulation_mode: false
  debug_logging: false
