export const PRICE_FEED_CONSTANTS = {
  UPDATE_INTERVAL: 5000, // 5 seconds
  HEARTBEAT_INTERVAL: 30000, // 30 seconds
  MAX_PRICE_AGE: 300000, // 5 minutes
  MIN_SOURCE_COUNT: 3,
  DEFAULT_DEVIATION_THRESHOLD: 0.01, // 1%
  SUPPORTED_PAIRS: ['NEO/USD', 'GAS/USD', 'FLM/USD', 'BTC/USD', 'ETH/USD'],
  PRICE_DECIMALS: 8,
  WS_ENDPOINT: 'ws://localhost:8080/ws',
  API_ENDPOINT: '/api/price-feeds',
  WEBSOCKET_EVENTS: {
    PRICE_UPDATE: 'PRICE_UPDATE',
    SOURCE_UPDATE: 'SOURCE_UPDATE',
    METRICS_UPDATE: 'METRICS_UPDATE',
    CONFIG_UPDATE: 'CONFIG_UPDATE'
  }
} as const;